server:
  port: 2600

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ramusfpdb
    username: root
    password: Pass1word2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
